# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=140)),
                ('c_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FacebookCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=63206)),
                ('like', models.CharField(max_length=10, null=True)),
                ('comment', models.CharField(max_length=10, null=True)),
                ('share', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('Retweet_user', models.CharField(max_length=100, null=True)),
                ('Retweet_post', models.CharField(max_length=140, null=True)),
                ('hashtag', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
