# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcrawl',
            name='status',
            field=models.CharField(max_length=5000),
        ),
    ]
