# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('Retweet_user', models.CharField(max_length=100)),
                ('Retweet_post', models.CharField(max_length=140)),
                ('hashtag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crawl',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
