# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0002_auto_20170820_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittercrawl',
            name='Retweet_post',
        ),
    ]
