# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0003_remove_twittercrawl_retweet_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=5000)),
                ('like', models.CharField(max_length=10, null=True)),
                ('comment', models.CharField(max_length=10, null=True)),
                ('share', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookTopik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('Retweet_user', models.CharField(max_length=100, null=True)),
                ('hashtag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTopik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='twitterdataset',
            name='topik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media_crawling.TwitterTopik'),
        ),
        migrations.AddField(
            model_name='facebookdataset',
            name='topik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media_crawling.FacebookTopik'),
        ),
    ]
