# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0004_auto_20170825_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcrawl',
            name='comment',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookcrawl',
            name='like',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookcrawl',
            name='share',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookdataset',
            name='comment',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookdataset',
            name='like',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookdataset',
            name='share',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
