# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0004_auto_20170825_1745'),
        ('social_media_crawling', '0004_facebookcrawl'),
    ]

    operations = [
    ]
