# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_crawling', '0005_auto_20170829_2125'),
        ('social_media_crawling', '0005_merge_20170826_2056'),
    ]

    operations = [
    ]
