# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_hasil_pencarian_keyword_word_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_Berita',
            fields=[
                ('id_berita', models.AutoField(primary_key=True, serialize=False)),
                ('judul_berita', models.CharField(max_length=500)),
            ],
        ),
    ]
