# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0008_auto_20170814_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_berita',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
