# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0009_auto_20170814_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabel_berita',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
