# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawling', '0010_auto_20170814_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='akun',
        ),
        migrations.AddField(
            model_name='preproses',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Akun',
        ),
    ]
