# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormalisasiKataDB',
            fields=[
                ('kataInformal', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('kataFormal', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KataDB',
            fields=[
                ('idKata', models.AutoField(primary_key=True, serialize=False)),
                ('kata', models.CharField(max_length=30)),
                ('sentiLabKata', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KataFormalDB',
            fields=[
                ('kataFormal', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SentimenDB',
            fields=[
                ('kataSentimen', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sentiLab', models.SmallIntegerField()),
                ('priorNetral', models.DecimalField(decimal_places=2, max_digits=3)),
                ('priorPositive', models.DecimalField(decimal_places=2, max_digits=3)),
                ('priorNegative', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SentimenKataMIDB',
            fields=[
                ('kataSentimen', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sentiLab', models.SmallIntegerField()),
                ('priorNetral', models.DecimalField(decimal_places=2, max_digits=3)),
                ('priorPositive', models.DecimalField(decimal_places=2, max_digits=3)),
                ('priorNegative', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
