# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopwordsIDDB',
            fields=[
                ('kataStopword', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
